name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ReneHezser
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.GHCRPAT }}
        # Log out from the Docker registry at the end of a job
        logout: true

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: "./"
        file: ./Dockerfile
        platforms: linux/amd64 #,linux/arm64,linux/arm/v7
        push: true
        tags: |
          ghcr.io/renehezser/docker/customhealthcheck:$(date +%s)
          ghcr.io/renehezser/docker/customhealthcheck:latest